### ISSUE TITLE
draftIds undefined, studio crashing when trying to Duplicate content

### ISSUE THREAD

**Issue by dotdev-support** [sanity-io/cross-dataset-duplicator#11]
Hi, 

I have followed the instruction from the readme but I am running into this error when I click Duplicate in the document actions. Let me know if you need further information

Error in the studio: 
```
TypeError: Cannot read properties of undefined (reading 'includes')
    at http://localhost:3333/static/js/app.bundle.js:235034:24
    at Array.map (<anonymous>)
    at DuplicatorTool (/static/js/app.bundle.js:235030:60)
    at renderWithHooks (/static/js/vendor.bundle.js:17961:18)
    at mountIndeterminateComponent (/static/js/vendor.bundle.js:20640:13)
    at beginWork (/static/js/vendor.bundle.js:21754:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3346:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3395:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3450:31)
    at beginWork$1 (/static/js/vendor.bundle.js:26361:7)
```

The line that creates the error: 
```
var _useState5 = (0, _react.useState)(docs.length ? docs.map(item => ({
    doc: item,
    include: true,
    status: null,
    hasDraft: draftIds.includes("drafts.".concat(item._id))
  })) : []),
```

`draftIds` is undefined which breaks the `includes`

**Comment by SimeonGriggs** [comment]
Thanks for reporting, should be fixed now in `0.3.4`
